name: Run Tests

on: [pull_request]


jobs:

  build-upload:
    runs-on: windows-latest
    steps:

      - uses: actions/setup-java@v1.3.0
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1.2.0
        with:
          channel: 'stable'

      - uses: actions/checkout@v2.0.0
      - run: flutter doctor -v
      - run : flutter channel dev
      - run: flutter upgrade
      - run: flutter pub get
      - run: flutter test
